#!/usr/bin/env bash
# Generate the Ansible inventory + group_vars (incl. fresh WireGuard keypairs) for the two validation VMs.
# Writes ../inventory.ini and ../group_vars/all.yml (both gitignored). Run before `vagrant up` + ansible.
set -euo pipefail
cd "$(dirname "$0")" || exit 1
command -v wg >/dev/null || { echo "need wireguard-tools (wg) on the host"; exit 1; }

CORE_PUB_IP=192.168.56.10
DOMAIN="${REDNET_DOMAIN:-rednet.test}"

CORE_PRIV=$(wg genkey); CORE_PUBKEY=$(echo "$CORE_PRIV" | wg pubkey)
FRONT_PRIV=$(wg genkey); FRONT_PUBKEY=$(echo "$FRONT_PRIV" | wg pubkey)

mkdir -p ../group_vars
cat > ../group_vars/all.yml <<YAML
# GENERATED by validate/gen-config.sh for the 2-VM validation. DO NOT COMMIT (gitignored).
rednet_domain: ${DOMAIN}
wan_iface: eth1                      # the host-only "public" NIC inside the VMs (vagrant: eth0=NAT, eth1=private_network)
wg_subnet: "10.13.13.0/24"
wg_core_ip: "10.13.13.1"
wg_front_ip: "10.13.13.2"
wg_listen_port: 51820
wg_core_endpoint: "${CORE_PUB_IP}:51820"
wg_core_private_key: "${CORE_PRIV}"
wg_core_public_key: "${CORE_PUBKEY}"
wg_front_private_key: "${FRONT_PRIV}"
wg_front_public_key: "${FRONT_PUBKEY}"
rednet_retention_days: 7
rednet_media_retention_days: 7
rednet_brand: REDnet
YAML

cat > ../inventory.ini <<INI
# GENERATED by validate/gen-config.sh. Vagrant SSH config — run \`vagrant ssh-config\` to confirm ports/keys.
[core]
core1 ansible_host=127.0.0.1 ansible_port=2222 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/core/virtualbox/private_key

[front]
front1 ansible_host=127.0.0.1 ansible_port=2200 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/front/virtualbox/private_key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
INI

echo "wrote ../group_vars/all.yml + ../inventory.ini"
echo "NOTE: confirm SSH ports with 'vagrant ssh-config' (Vagrant assigns 2222.. dynamically) and fix inventory.ini if needed,"
echo "      or use Vagrant's ansible provisioner instead. wan_iface defaults to eth1 (the private_network NIC) — verify with 'ip a' in the VM."
