// PWA milestone A — prove the SILENT E2EE bootstrap (no user-visible recovery key / UIA).
// Heart of SPEC §5 Track A. Writes the verdict to result.json (piped-stdout truncation-safe).
import * as sdk from "matrix-js-sdk";
import fs from "node:fs";

try { sdk.logger?.setLevel?.("ERROR"); } catch {}

const HS = process.env.HS || "http://localhost:8008";
const LOCALPART = process.env.LOCALPART || "alice";
const PASS = process.env.PASS || "password123";
const log = (...a) => console.log(...a);
const errs = [];

async function main() {
  // 1) login
  const tmp = sdk.createClient({ baseUrl: HS });
  const cred = await tmp.login("m.login.password", {
    identifier: { type: "m.id.user", user: LOCALPART }, password: PASS,
    initial_device_display_name: "rednet-onboarding-proto",
  });
  log("logged in:", cred.user_id, "device:", cred.device_id);

  // 2) full client + crypto.
  // The app holds the secret-storage (recovery) key in memory and hands it back to the SDK
  // via getSecretStorageKey — so the SDK can export cross-signing keys into 4S without ever
  // prompting the user. This is what makes the recovery key invisible.
  let appHeldKey = null;
  const ssKeys = {};
  const client = sdk.createClient({
    baseUrl: HS, userId: cred.user_id, accessToken: cred.access_token, deviceId: cred.device_id,
    cryptoCallbacks: {
      getSecretStorageKey: async ({ keys }) => {
        const keyId = Object.keys(keys)[0];
        if (appHeldKey?.privateKey) return [keyId, appHeldKey.privateKey];
        if (ssKeys[keyId]) return [keyId, ssKeys[keyId]];
        return null;
      },
      cacheSecretStorageKey: (keyId, _info, privateKey) => { ssKeys[keyId] = privateKey; },
    },
  });
  await client.initRustCrypto({ useIndexedDB: false });
  const crypto = client.getCrypto();
  // start the sync loop so background crypto requests (/keys/query, backup) actually run.
  // (Without this the bootstrap awaits hang and Node exits 0 on an empty event loop.)
  await client.startClient({ initialSyncLimit: 1 });
  await new Promise((res, rej) => {
    const t = setTimeout(() => rej(new Error("first sync timed out")), 30000);
    client.on("sync", (s) => { if (s === "PREPARED" || s === "SYNCING") { clearTimeout(t); res(); } });
  });
  log("rust crypto initialized; client synced");

  // 3) SILENT cross-signing (MSC3967: first device-signing upload needs no UIA)
  await crypto.bootstrapCrossSigning({
    authUploadDeviceSigningKeys: async (makeRequest) => { await makeRequest({}); },
  });
  log("cross-signing bootstrapped");

  // 4) SILENT secret storage + key backup; recovery key generated by US, never shown
  await crypto.bootstrapSecretStorage({
    setupNewSecretStorage: true,
    setupNewKeyBackup: true,
    createSecretStorageKey: async () => {
      const key = await crypto.createRecoveryKeyFromPassphrase();
      appHeldKey = key; // app custodies (escrow/discard per policy) — NOT shown to the user
      return key;
    },
  });
  log("secret storage bootstrapped");

  // ensure key backup is actually created+enabled
  let backupVer = (await crypto.getActiveSessionBackupVersion?.()) ?? null;
  if (!backupVer) {
    try { await crypto.resetKeyBackup(); } catch (e) { errs.push("resetKeyBackup: " + e.message); }
    try { await crypto.checkKeyBackupAndEnable?.(); } catch (e) { errs.push("checkKeyBackup: " + e.message); }
    backupVer = (await crypto.getActiveSessionBackupVersion?.()) ?? null;
  }

  // also confirm via the server directly
  let serverBackup = null;
  try {
    const r = await fetch(`${HS}/_matrix/client/v3/room_keys/version`, { headers: { Authorization: `Bearer ${cred.access_token}` } });
    serverBackup = r.ok ? (await r.json()).version : null;
  } catch (e) { errs.push("server backup check: " + e.message); }

  // 5) verify
  const xs = await crypto.getCrossSigningStatus();
  const result = {
    crossSigning_publicKeysOnDevice: !!xs?.publicKeysOnDevice,
    crossSigning_privateKeysInSecretStorage: !!xs?.privateKeysInSecretStorage,
    keyBackup_activeVersion: backupVer,
    keyBackup_onServer: serverBackup,
    recoveryKey_generatedByApp: !!appHeldKey?.encodedPrivateKey,
    recoveryKey_lengthChars: appHeldKey?.encodedPrivateKey?.length ?? null,
    recoveryKey_shownToUser: false, // by construction — we never print/display it
    errors: errs,
  };
  const pass =
    result.crossSigning_publicKeysOnDevice &&
    result.crossSigning_privateKeysInSecretStorage &&
    !!(result.keyBackup_activeVersion || result.keyBackup_onServer) &&
    result.recoveryKey_generatedByApp;
  result.PASS = pass;

  fs.writeFileSync("result.json", JSON.stringify(result, null, 2));
  log("\n=== RESULT ===\n" + JSON.stringify(result, null, 2));

  try { client.stopClient(); await crypto.stop?.(); } catch {}
  process.exitCode = pass ? 0 : 2;
  setTimeout(() => process.exit(pass ? 0 : 2), 300); // flush + hard-exit (crypto keeps handles open)
}

main().catch((e) => {
  const out = { PASS: false, fatal: e?.message || String(e), stack: e?.stack?.split("\n").slice(0, 5) };
  try { fs.writeFileSync("result.json", JSON.stringify(out, null, 2)); } catch {}
  console.error("\nERROR:", out.fatal);
  setTimeout(() => process.exit(1), 300);
});
